# Generated by Django 4.2.3 on 2024-04-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='checkout_url',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
    ]
