# Generated by Django 5.0.3 on 2024-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_max_otp_try_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
