# Generated by Django 5.0.3 on 2024-04-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='otp_expiry',
            new_name='otp_expirty',
        ),
    ]
