# Generated by Django 5.0.3 on 2024-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rename_otp_expirty_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
