# Generated by Django 4.2.3 on 2024-04-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
