# Generated by Django 5.0.3 on 2024-03-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0001_initial'),
        ('Products', '__first__'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmer',
            new_name='Farmers',
        ),
        migrations.CreateModel(
            name='FarmerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('farmer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Farmers.farmers')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.prodcuts')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.uoms')),
            ],
        ),
    ]
