# Generated by Django 4.2.3 on 2024-04-04 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Farmers', '0002_rename_farmer_farmers_farmerproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmers',
            new_name='Farmer',
        ),
    ]
