# Generated by Django 5.0.3 on 2024-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0003_rename_farmers_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproducts',
            name='image1',
            field=models.ImageField(null=True, upload_to='uploads/products'),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='image2',
            field=models.ImageField(null=True, upload_to='uploads/products'),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='image3',
            field=models.ImageField(null=True, upload_to='uploads/products'),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='last_added',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='location_longtude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='location_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
