# Generated by Django 5.0.3 on 2024-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0004_farmerproducts_image1_farmerproducts_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproducts',
            name='image1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerproducts',
            name='image2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerproducts',
            name='image3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
