# Generated by Django 4.2.3 on 2024-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_address_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='signiture',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
