# Generated by Django 5.0.3 on 2024-04-09 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Orders", "0002_alter_orders_delivery_address_name_and_more"),
        ("Products", "0004_alter_product_image1_alter_product_image2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Orders",
            new_name="Order",
        ),
    ]
