# Generated by Django 5.0.3 on 2024-03-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UOMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prodcuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_added', models.DateField(null=True)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('location_longtude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('image1', models.ImageField(upload_to='uploads/products')),
                ('image2', models.ImageField(upload_to='uploads/products')),
                ('image3', models.ImageField(upload_to='uploads/products')),
                ('product_description', models.CharField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.categories')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.uoms')),
            ],
        ),
    ]
