# Generated by Django 4.2.3 on 2024-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcuts',
            name='product_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
