# Generated by Django 5.0.3 on 2024-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0003_rename_prodcuts_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.ImageField(null=True, upload_to="uploads/products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(null=True, upload_to="uploads/products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(null=True, upload_to="uploads/products"),
        ),
    ]
