# Generated by Django 5.0.3 on 2024-04-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location_longtude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
    ]
